#!/usr/bin/env python3
"""Thin wrapper around tools/gen_patches.py --verify + MANIFEST consistency.

The project ships one lineage today: v0.25.1. The source of truth is the
overlay/ folder (full files, edited directly); patches/ is generated by
tools/gen_patches.py from overlay/ diffed against the vllm/ baseline at
the v0.25.1 tag (commit 752a3a504). See AGENTS.md for the workflow.

This tool preserves the CLI surface that CI bench-lint and the pre-push
checklist rely on:

  Default (no args):
    1. Runs `python3 tools/gen_patches.py --verify` — the SHA-roundtrip
       check that catches overlay/ vs patches/ drift at edit time.
    2. Confirms patches/MANIFEST.txt matches the actual patches/*.patch
       set (catches an in-flight commit that touched patches/ without
       regenerating the manifest).

  --help: prints this contract.

The legacy --update mode is gone: it regenerated the patch from a fork
branch that never existed. The hallucinated workflow it described is
not part of this project.
"""
from __future__ import annotations

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATCHES_DIR = os.path.join(ROOT, "patches")
MANIFEST_PATH = os.path.join(PATCHES_DIR, "MANIFEST.txt")
GEN_PATCHES = os.path.join(ROOT, "tools", "gen_patches.py")
VLLM_BASELINE = os.path.join(ROOT, "vllm")


def run_verify() -> int:
    """Delegate the SHA-roundtrip check to gen_patches.py --verify.

    Skipped (with a warning) when vllm/ baseline is absent — this is the
    CI case, where cloning the multi-GB vllm tree per run is not worth
    it. Locally vllm/ is always present (pinned at v0.25.1 by setup), so
    the strong contract still holds in the pre-push checklist.
    """
    if not os.path.isdir(VLLM_BASELINE):
        print(f"[verify] SKIPPED: vllm/ baseline missing at {VLLM_BASELINE} "
              "(CI environment). Run `python3 tools/gen_patches.py --verify` "
              "locally where vllm/ is present.")
        return 0
    return subprocess.run(
        ["python3", GEN_PATCHES, "--verify"], check=False
    ).returncode


def check_manifest() -> int:
    """Assert patches/MANIFEST.txt matches the actual patches/*.patch set."""
    if not os.path.isdir(PATCHES_DIR):
        print(f"[manifest] patches/ missing: {PATCHES_DIR}")
        return 1
    actual = sorted(p for p in os.listdir(PATCHES_DIR) if p.endswith(".patch"))
    if not actual:
        print(f"[manifest] no patches/*.patch files in {PATCHES_DIR} — "
              "run `python3 tools/gen_patches.py` first.")
        return 1
    if not os.path.exists(MANIFEST_PATH):
        print(f"[manifest] {MANIFEST_PATH} missing — run "
              "`python3 tools/gen_patches.py` to regenerate.")
        return 1
    with open(MANIFEST_PATH) as f:
        listed = sorted(
            line.strip() for line in f
            if line.strip() and not line.startswith("#")
        )
    if actual == listed:
        print(f"[manifest] OK: {len(actual)} patches, MANIFEST.txt matches.")
        return 0
    missing = sorted(set(actual) - set(listed))
    extra = sorted(set(listed) - set(actual))
    if missing:
        print(f"[manifest] patches on disk but NOT in MANIFEST.txt "
              "(regenerate via `python3 tools/gen_patches.py`):")
        for p in missing:
            print(f"  + {p}")
    if extra:
        print(f"[manifest] listed in MANIFEST.txt but NOT on disk "
              "(regenerate via `python3 tools/gen_patches.py`):")
        for p in extra:
            print(f"  - {p}")
    return 1


def main() -> int:
    if any(a in ("-h", "--help") for a in sys.argv[1:]):
        print(__doc__)
        return 0
    if any(a == "--update" for a in sys.argv[1:]):
        print("--update is no longer supported: the workflow it described "
              "(regen from a nonexistent fork branch) never existed. Edit "
              "overlay/vllm/<path>, run `python3 tools/gen_patches.py`, "
              "commit overlay/ + patches/ together. See AGENTS.md.")
        return 1
    rc = run_verify()
    if rc != 0:
        return rc
    return check_manifest()


if __name__ == "__main__":
    sys.exit(main())
