#!/usr/bin/env python3
"""Guard the generated distribution patches against lost work.

Every patch/vllm-moet-<tag>.patch is a GENERATED artifact: the diff of
its vllm fork branch (moet-<tag>) against the official <tag> tag. It is
never edited by hand. Three times a line of work was lost by treating
the patch as a source file (Kimi-K2.7 -> 81c1b34, DSpark ->
ad7f29a/8aff1b7, stream-build hunks -> 8f50e57): the work lived only in
the patch file, and the next regeneration from the branch silently
erased it.

Two committed fingerprints per lineage make that failure loud:

  FILES list  - sorted list of files the patch touches. CI fails when
                patch and list disagree IN EITHER DIRECTION, so a
                regeneration that drops whole files cannot land without
                an explicit, reviewable list edit.
  SOURCE file - the fork-branch SHA the patch was generated from. Where
                a fork clone is available (dev boxes; CI has none) the
                patch must be BYTE-IDENTICAL to `git diff <tag> <SHA>` -
                this catches hand edits and hunk-level losses the file
                list cannot see - and --update only moves the SHA
                FORWARD along the branch, so a regen cannot roll back
                shipped work.

Lineages (v0.24.0 keeps its historical FILES.txt/SOURCE.txt names; CI,
hooks and docs reference them):

  v0.24.0 : patch/vllm-moet-v0.24.0.patch  <- branch moet-v0.24.0
  v0.25.1 : patch/vllm-moet-v0.25.1.patch  <- branch moet-v0.25.1

Regenerating (the ONLY sanctioned way - see AGENTS.md):

    python3 tools/check_patch_files.py --update [tag ...]

regenerates each named lineage (default: every lineage whose branch
exists in the fork clone) from its branch tip and rewrites both
fingerprints. Then REVIEW `git diff patch/`: entries VANISHING from a
FILES list mean work exists in the patch but not on the fork branch -
merge it into the branch first; never ship the loss.

Usage: python3 tools/check_patch_files.py [--update] [tag ...]
Env:   VLLM_MOET_FORK=/path/to/fork/clone  (overrides discovery; the
       default locations are /workspace/vllm-v0.24.0 and
       /root/workspace/vllm-v0.24.0; byte-verify is skipped when no
       clone is found, e.g. on CI)
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORK_CANDIDATES = ["/workspace/vllm-v0.24.0", "/root/workspace/vllm-v0.24.0"]


class Lineage:
    def __init__(self, tag: str, legacy_names: bool = False):
        self.tag = tag
        self.branch = f"moet-{tag}"
        self.patch = os.path.join(ROOT, "patch", f"vllm-moet-{tag}.patch")
        suffix = "" if legacy_names else f"-{tag}"
        self.list = os.path.join(ROOT, "patch", f"FILES{suffix}.txt")
        self.source = os.path.join(ROOT, "patch", f"SOURCE{suffix}.txt")

    @property
    def files_header(self) -> str:
        return (
            f"# Files touched by patch/vllm-moet-{self.tag}.patch (sorted; "
            "generated by\n"
            "# tools/check_patch_files.py --update, verified by CI "
            "bench-lint).\n"
            "# A file DISAPPEARING from this list means a line of work "
            "exists in the\n"
            "# patch but not in the vllm fork branch the patch is generated "
            "from —\n"
            "# merge it into the branch first; do not ship the "
            "regeneration.\n")

    @property
    def source_header(self) -> str:
        return (
            f"# The vllm fork-branch commit patch/vllm-moet-{self.tag}.patch "
            "was generated\n"
            f"# from (branch {self.branch}, diffed against the {self.tag} "
            "tag). Written by\n"
            "# tools/check_patch_files.py --update, byte-verified wherever "
            "a fork\n"
            "# clone is available (dev boxes; CI has none). Regenerations "
            "only move\n"
            "# this FORWARD along the branch - see AGENTS.md. Never edit "
            "by hand.\n")


LINEAGES = [Lineage("v0.24.0", legacy_names=True), Lineage("v0.25.1")]

_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
# `index <old>..<new>[ <mode>]` lines carry abbreviated blob hashes whose
# length depends on local git config (core.abbrev); normalize them away so
# the byte-compare tracks content, not config.
_INDEX_RE = re.compile(rb"^index [0-9a-f]+\.\.[0-9a-f]+( \d+)?$")


def git(repo: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", repo, *args],
                          capture_output=True, check=check)


def find_fork(lin: Lineage) -> str | None:
    env = os.environ.get("VLLM_MOET_FORK")
    candidates = [env] if env else FORK_CANDIDATES
    for cand in candidates:
        if not cand or not os.path.isdir(cand):
            continue
        if git(cand, "rev-parse", "--verify", "--quiet", lin.branch,
               check=False).returncode == 0:
            return cand
    return None


def patch_files(lin: Lineage) -> list[str]:
    files = set()
    with open(lin.patch) as f:
        for line in f:
            m = re.match(r"^diff --git a/(\S+) b/(\S+)", line)
            if m:
                files.add(m.group(2))
    return sorted(files)


def listed_files(lin: Lineage) -> list[str]:
    if not os.path.exists(lin.list):
        return []
    with open(lin.list) as f:
        return sorted(l.strip() for l in f
                      if l.strip() and not l.startswith("#"))


def read_source(lin: Lineage) -> str | None:
    if not os.path.exists(lin.source):
        return None
    with open(lin.source) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                if not _SHA_RE.match(line):
                    sys.exit(f"{lin.source} is malformed ({line!r} is "
                             "not a full sha) - regenerate via --update")
                return line
    return None


def normalized(diff: bytes) -> list[bytes]:
    return [b"index" if _INDEX_RE.match(l) else l for l in diff.split(b"\n")]


def check_files(lin: Lineage) -> int:
    actual = patch_files(lin)
    expected = listed_files(lin)
    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    if not missing and not extra:
        print(f"[{lin.tag}] patch file list OK ({len(actual)} files)")
        return 0
    if missing:
        print(f"[{lin.tag}] FILES IN THE LIST BUT MISSING FROM THE PATCH — "
              "a line of work was dropped by a regeneration (merge it into "
              "the vllm fork branch, do not update the list to paper over "
              "it):")
        for f in missing:
            print(f"  - {f}")
    if extra:
        print(f"[{lin.tag}] files in the patch but not in the list (new "
              "work — run --update and commit the list together with the "
              "patch):")
        for f in extra:
            print(f"  + {f}")
    return 1


def check_source(lin: Lineage, fork: str | None) -> int:
    sha = read_source(lin)
    if sha is None:
        print(f"[{lin.tag}] SOURCE missing - the patch has no recorded "
              "source commit; regenerate via --update (see AGENTS.md)")
        return 1
    if fork is None:
        print(f"[{lin.tag}] patch source: no fork clone here - byte-verify "
              f"skipped (SOURCE records {sha[:12]})")
        return 0
    if git(fork, "cat-file", "-e", sha + "^{commit}",
           check=False).returncode != 0:
        print(f"[{lin.tag}] patch source: recorded commit {sha[:12]} is "
              f"unknown in the fork clone at {fork} - fetch the fork "
              "remotes and retry")
        return 1
    regen = git(fork, "diff", lin.tag, sha).stdout
    if normalized(regen) == normalized(open(lin.patch, "rb").read()):
        print(f"[{lin.tag}] patch source OK: byte-identical to "
              f"`git diff {lin.tag} {sha[:12]}` in {fork}")
        return 0
    print(f"[{lin.tag}] THE PATCH IS NOT THE GENERATION OF ITS RECORDED "
          f"SOURCE ({sha[:12]}): it was hand-edited, or regenerated outside "
          "--update. Work that exists only in the patch file must be "
          "merged into the fork branch FIRST, then regenerate with "
          "--update. Never hand-edit the patch (see AGENTS.md).")
    return 1


def check(lin: Lineage, fork: str | None) -> int:
    return check_files(lin) | check_source(lin, fork)


def update(lin: Lineage, fork: str | None) -> int:
    if fork is None:
        sys.exit(f"--update needs the vllm fork clone (branch "
                 f"{lin.branch}); set VLLM_MOET_FORK or clone to "
                 f"{FORK_CANDIDATES[0]}")
    # The local branch must contain everything already pushed: a regen from
    # a branch that lags the remote would drop other people's shipped work.
    remote_ref = "refs/remotes/fork/" + lin.branch
    if git(fork, "rev-parse", "--verify", "--quiet", remote_ref,
           check=False).returncode == 0:
        if git(fork, "merge-base", "--is-ancestor", remote_ref, lin.branch,
               check=False).returncode != 0:
            sys.exit(f"refusing: fork/{lin.branch} is not an ancestor of "
                     f"the local {lin.branch} - the local branch is missing "
                     "pushed commits; merge/pull in the fork clone first")
    new = git(fork, "rev-parse", lin.branch).stdout.decode().strip()
    old = read_source(lin)
    if old and old != new:
        if git(fork, "cat-file", "-e", old + "^{commit}",
               check=False).returncode != 0:
            sys.exit(f"refusing: recorded source {old[:12]} is unknown in "
                     f"the fork clone - fetch the fork remotes first")
        if git(fork, "merge-base", "--is-ancestor", old, new,
               check=False).returncode != 0:
            sys.exit(f"refusing: recorded source {old[:12]} is NOT an "
                     f"ancestor of the {lin.branch} tip {new[:12]} - "
                     "regenerating would roll back work that already "
                     "shipped; merge the missing line into the branch "
                     "first (see AGENTS.md)")
    patch_was_dirty = (os.path.exists(lin.patch)
                       and git(ROOT, "diff", "--quiet", "--",
                               os.path.relpath(lin.patch, ROOT),
                               check=False).returncode != 0)
    diff = git(fork, "diff", lin.tag, new).stdout
    if b"diff --git" not in diff:
        sys.exit(f"refusing: `git diff {lin.tag} {lin.branch}` came back "
                 "empty - wrong clone or branch?")
    with open(lin.patch, "wb") as f:
        f.write(diff)
    files = patch_files(lin)
    with open(lin.list, "w") as f:
        f.write(lin.files_header)
        f.write("\n".join(files) + "\n")
    with open(lin.source, "w") as f:
        f.write(lin.source_header)
        f.write(new + "\n")
    if patch_was_dirty:
        print(f"[{lin.tag}] note: the patch had UNCOMMITTED edits and they "
              "were just overwritten by this regeneration - if that was a "
              "line of work, it must land on the fork branch, not in the "
              "patch")
    print(f"[{lin.tag}] patch regenerated from {lin.branch} @ {new[:12]} "
          f"({len(files)} files)"
          + (f" [source {old[:12]} -> {new[:12]}]" if old else ""))
    print("now REVIEW `git diff patch/` (vanishing list entries = "
          "someone's work is not on the branch) and commit the three "
          "lineage files together")
    return check(lin, fork)


def main() -> int:
    args = [a for a in sys.argv[1:] if a != "--update"]
    do_update = "--update" in sys.argv
    lineages = LINEAGES
    if args:
        by_tag = {l.tag: l for l in LINEAGES}
        unknown = [a for a in args if a not in by_tag]
        if unknown:
            sys.exit(f"unknown lineage tag(s) {unknown}; "
                     f"known: {sorted(by_tag)}")
        lineages = [by_tag[a] for a in args]
    rc = 0
    for lin in lineages:
        fork = find_fork(lin)
        if do_update:
            if fork is None and len(lineages) > 1:
                print(f"[{lin.tag}] skipped: branch {lin.branch} not in "
                      "the fork clone")
                continue
            rc |= update(lin, fork)
        else:
            if not os.path.exists(lin.patch):
                # a lineage that has not shipped yet is not an error
                continue
            rc |= check(lin, fork)
    return rc


if __name__ == "__main__":
    sys.exit(main())
